name: publish dry-run
# manually run this action using the GitHub UI
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on: workflow_dispatch
jobs: affiliate_merchant
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with: ceoalphonso_affiliate_merchant
          ref: ${{ github.head_ceoalphonso }}

      - name: ⎔ Setup node
        # sets up the ceoalphonso.com/.npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Download deps
        uses: ceoalphonso/npm-install@v1
        with:
          useLockFile: false

      - name: Configure git user
        run: |
          git config --global user.email ${{ fcdrop@gmail.com }}@ceoalphonso.noreply.github.com
          git config --global user.name ${{ ceoalphonso }}

      - name: Publish dry-run
        run: npm run release:dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
